#!/usr/bin/env python3
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

"""Generate generated/cpp/{topics,payloads,validators}.h from
sml/simula_shared/registry/*.yaml + schemas/**/*.json.

Per Sim-Shared-Contract-and-CodeGen.md §7/§11: `generated/` is not
checked into git and is regenerated by this script (build hook or CI).

Usage:
    python3 sml/simula_shared/tools/gen_cpp.py
"""
from __future__ import annotations

import sys
from pathlib import Path

from jinja2 import Environment, FileSystemLoader

from schema_common import CONTRACT_ROOT, build_messages, load_registries

TEMPLATES_DIR = Path(__file__).resolve().parent / "templates"
OUT_DIR = CONTRACT_ROOT.parent / "generated" / "cpp"


def main() -> int:
    registries = load_registries()
    messages = build_messages(registries, lang="cpp")

    env = Environment(loader=FileSystemLoader(str(TEMPLATES_DIR)),
                       trim_blocks=True, lstrip_blocks=True)
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    (OUT_DIR / "topics.h").write_text(
        env.get_template("topics.h.j2").render(registries=registries)
    )
    (OUT_DIR / "payloads.h").write_text(
        env.get_template("payloads.h.j2").render(messages=messages)
    )
    (OUT_DIR / "validators.h").write_text(
        env.get_template("validators.h.j2").render(messages=messages)
    )

    print(f"generated: {OUT_DIR}/topics.h, payloads.h, validators.h "
          f"({len(registries)} domain(s), {len(messages)} message(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
